# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import filer.fields.file
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hphrase',
            options={'verbose_name': 'H-Phrase', 'verbose_name_plural': 'H-Phrases'},
        ),
        migrations.AlterModelOptions(
            name='hphrasecheck',
            options={'verbose_name': 'H-Phrase', 'verbose_name_plural': 'H-Phrases'},
        ),
        migrations.AlterModelOptions(
            name='pphrase',
            options={'verbose_name': 'P-Phrase', 'verbose_name_plural': 'P-Phrases'},
        ),
        migrations.AlterModelOptions(
            name='pphrasecheck',
            options={'verbose_name': 'P-Phrase', 'verbose_name_plural': 'P-Phrases'},
        ),
        migrations.AlterModelOptions(
            name='synonym',
            options={'verbose_name': 'Synonym', 'verbose_name_plural': 'Synonyms'},
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='cmr',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='hazardous',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='extendedsafetydatasheet',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='safetydatasheet',
            name='instruction',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='has_instructions',
        ),
        migrations.AddField(
            model_name='hphrase',
            name='cmr',
            field=models.IntegerField(default=9, verbose_name='CMR', choices=[(9, b'Not relevant'), (1, b'Category 1A/1B'), (2, b'Category 2')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='archive',
            field=models.BooleanField(default=False, verbose_name='Archive'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='article',
            field=models.CharField(max_length=100, null=True, verbose_name='Article Number', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='cas',
            field=models.CharField(max_length=100, null=True, verbose_name='CAS', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='comment',
            field=models.TextField(null=True, verbose_name='Comment'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='comment_de',
            field=models.TextField(null=True, verbose_name='Comment'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='comment_en',
            field=models.TextField(null=True, verbose_name='Comment'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='comment_nl',
            field=models.TextField(null=True, verbose_name='Comment'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='components_registered',
            field=models.BooleanField(default=False, verbose_name='Components Registered'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='departments',
            field=models.ManyToManyField(to='chemicals.Department', verbose_name='Departments', through='chemicals.Supplier', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='einecs',
            field=models.CharField(max_length=100, null=True, verbose_name='EINECS', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='hphrases',
            field=models.ManyToManyField(to='chemicals.HPhrase', verbose_name='H-Phrases', through='chemicals.HPhraseRelation', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='locations',
            field=models.ManyToManyField(to='chemicals.Location', verbose_name='Locations', through='chemicals.Stock', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='needed',
            field=models.BooleanField(default=False, verbose_name='Permanently Needed'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='pphrases',
            field=models.ManyToManyField(to='chemicals.PPhrase', verbose_name='P-Phrases', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='preparation',
            field=models.BooleanField(default=False, verbose_name='Preparation'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='reach_vo',
            field=models.BooleanField(default=False, verbose_name='Listed in annex XIV REACH regulation'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='registration_number',
            field=models.CharField(max_length=100, null=True, verbose_name='Registration Number', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='rphrases',
            field=models.ManyToManyField(to='chemicals.RPhrase', verbose_name='R-Phrases', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='seveso_categories',
            field=models.ManyToManyField(to='chemicals.SevesoCategory', verbose_name='Seveso Categories', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='signal',
            field=models.CharField(default=b'n', max_length=1, verbose_name='Signal', choices=[(b'd', 'danger'), (b'w', 'warning'), (b'n', 'no signal')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='synonyms',
            field=models.ManyToManyField(to='chemicals.Synonym', verbose_name='Synonyms', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='chemical',
            name='wgk',
            field=models.ManyToManyField(to='chemicals.WGK', verbose_name='WGK', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.TextField(null=True, verbose_name='Address', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='country',
            field=models.CharField(max_length=100, null=True, verbose_name='Country', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Email', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='fax',
            field=models.CharField(max_length=100, null=True, verbose_name='Fax', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='info',
            field=models.TextField(null=True, verbose_name='Information', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=400, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='persons',
            field=models.ManyToManyField(to='chemicals.Person', verbose_name='Persons', through='chemicals.Role'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Phone', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='contact',
            name='web',
            field=models.CharField(max_length=100, null=True, verbose_name='Web', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='department',
            name='plant',
            field=models.ForeignKey(verbose_name='Plant', to='chemicals.Plant'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created on'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='doctype',
            field=models.CharField(max_length=100, verbose_name='Document Type'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=filer.fields.file.FilerFileField(verbose_name='File', blank=True, to='filer.File', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extendedsafetydatasheet',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extendedsafetydatasheet',
            name='country_code',
            field=models.CharField(max_length=2, verbose_name='Country Code', choices=[(b'en', 'English'), (b'de', 'German'), (b'nl', 'Dutch')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extendedsafetydatasheet',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created on'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extendedsafetydatasheet',
            name='file',
            field=filer.fields.file.FilerFileField(verbose_name='File', blank=True, to='filer.File', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extendedsafetydatasheet',
            name='issue_date',
            field=models.DateField(null=True, verbose_name='Issue Date', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='extendedsafetydatasheet',
            name='supplier',
            field=models.ForeignKey(verbose_name='Supplier', to='chemicals.Contact'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphrase',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphrase',
            name='description_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphrase',
            name='description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphrase',
            name='description_nl',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphrase',
            name='seveso_relevant',
            field=models.BooleanField(default=False, verbose_name='Seveso Relevant'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphraserelation',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphraserelation',
            name='hphrase',
            field=models.ForeignKey(verbose_name='H-Phrase', to='chemicals.HPhrase'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphraserelation',
            name='info',
            field=models.TextField(verbose_name='Information', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphraserelation',
            name='info_de',
            field=models.TextField(null=True, verbose_name='Information', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphraserelation',
            name='info_en',
            field=models.TextField(null=True, verbose_name='Information', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='hphraserelation',
            name='info_nl',
            field=models.TextField(null=True, verbose_name='Information', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='department',
            field=models.ForeignKey(verbose_name='Department', to='chemicals.Department'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='academic_title',
            field=models.CharField(max_length=100, null=True, verbose_name='Academic Title', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=100, null=True, verbose_name='Email', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='fax',
            field=models.CharField(max_length=100, null=True, verbose_name='Fax', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='givenname',
            field=models.CharField(max_length=200, verbose_name='Given name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.CharField(max_length=100, null=True, verbose_name='Phone', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='surname',
            field=models.CharField(max_length=100, null=True, verbose_name='Surname', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='person',
            name='title',
            field=models.CharField(max_length=100, null=True, verbose_name='Title', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pictogram',
            name='code',
            field=models.CharField(max_length=100, verbose_name='Code'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pictogram',
            name='image',
            field=filer.fields.image.FilerImageField(verbose_name='Image', blank=True, to='filer.Image', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='plant',
            name='name_de',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='plant',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='plant',
            name='name_nl',
            field=models.CharField(max_length=100, null=True, verbose_name='Name'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pphrase',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pphrase',
            name='description_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pphrase',
            name='description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='pphrase',
            name='description_nl',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachdocument',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachdocument',
            name='country_code',
            field=models.CharField(max_length=2, verbose_name='Country Code', choices=[(b'en', 'English'), (b'de', 'German'), (b'nl', 'Dutch')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachdocument',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created on'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachdocument',
            name='file',
            field=filer.fields.file.FilerFileField(verbose_name='File', blank=True, to='filer.File', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachinformation',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachinformation',
            name='description',
            field=models.TextField(verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachinformation',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachinformation',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='reachinformation',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='risk',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='risk',
            name='riskindication',
            field=models.ForeignKey(verbose_name='Risk Indication', to='chemicals.RiskIndication'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='role',
            name='contact',
            field=models.ForeignKey(verbose_name='Contact', to='chemicals.Contact'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='role',
            name='person',
            field=models.ForeignKey(verbose_name='Person', to='chemicals.Person'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(max_length=1, verbose_name='Role', choices=[(b'r', b'REACH'), (b'c', 'Chemical')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='rphrase',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='rphrase',
            name='description_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='rphrase',
            name='description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='rphrase',
            name='description_nl',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='safetydatasheet',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='safetydatasheet',
            name='country_code',
            field=models.CharField(max_length=2, verbose_name='Country Code', choices=[(b'en', 'English'), (b'de', 'German'), (b'nl', 'Dutch')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='safetydatasheet',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created on'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='safetydatasheet',
            name='file',
            field=filer.fields.file.FilerFileField(verbose_name='File', blank=True, to='filer.File', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='safetydatasheet',
            name='issue_date',
            field=models.DateField(null=True, verbose_name='Issue Date', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='safetydatasheet',
            name='supplier',
            field=models.ForeignKey(verbose_name='Supplier', to='chemicals.Contact'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesocategory',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesocategory',
            name='description_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesocategory',
            name='description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesocategory',
            name='description_nl',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesodocument',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesodocument',
            name='country_code',
            field=models.CharField(max_length=2, verbose_name='Country Code', choices=[(b'en', 'English'), (b'de', 'German'), (b'nl', 'Dutch')]),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesodocument',
            name='created',
            field=models.DateField(auto_now_add=True, verbose_name='Created on'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesodocument',
            name='file',
            field=filer.fields.file.FilerFileField(verbose_name='File', blank=True, to='filer.File', null=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesoinformation',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesoinformation',
            name='description',
            field=models.TextField(verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesoinformation',
            name='description_de',
            field=models.TextField(null=True, verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesoinformation',
            name='description_en',
            field=models.TextField(null=True, verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='sevesoinformation',
            name='description_nl',
            field=models.TextField(null=True, verbose_name='Description'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='stock',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='stock',
            name='location',
            field=models.ForeignKey(verbose_name='Location', to='chemicals.Location'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='storageclass',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='storageclass',
            name='description_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='storageclass',
            name='description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='storageclass',
            name='description_nl',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.ForeignKey(verbose_name='Contact', to='chemicals.Contact'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='supplier',
            name='department',
            field=models.ForeignKey(verbose_name='Department', to='chemicals.Department'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='toxdata',
            name='chemical',
            field=models.ForeignKey(verbose_name='Chemical', to='chemicals.Chemical'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='toxdata',
            name='oekotox',
            field=models.BooleanField(default=False, verbose_name='Oekotox'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='toxdata',
            name='supplier',
            field=models.ForeignKey(verbose_name='Supplier', to='chemicals.Contact'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='toxdata',
            name='tox',
            field=models.BooleanField(default=False, verbose_name='Tox'),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='wgk',
            name='description',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='wgk',
            name='description_de',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='wgk',
            name='description_en',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
        migrations.AlterField(
            model_name='wgk',
            name='description_nl',
            field=models.CharField(max_length=400, null=True, verbose_name='Description', blank=True),
            preserve_default=True,
        ),
    ]
