DELETE FROM `she`.`chemicals_stock`;
ALTER TABLE `she`.`chemicals_stock` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_location`;
ALTER TABLE `she`.`chemicals_location` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_department`;
ALTER TABLE `she`.`chemicals_department` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_role`;
ALTER TABLE `she`.`chemicals_role` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_supplier`;
ALTER TABLE `she`.`chemicals_supplier` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_contact`;
ALTER TABLE `she`.`chemicals_contact` AUTO_INCREMENT = 1;
