DELETE FROM `intranet`.`chemicals_stock`;
ALTER TABLE `intranet`.`chemicals_stock` AUTO_INCREMENT = 1;
DELETE FROM `intranet`.`chemicals_location`;
ALTER TABLE `intranet`.`chemicals_location` AUTO_INCREMENT = 1;
DELETE FROM `intranet`.`chemicals_department`;
ALTER TABLE `intranet`.`chemicals_department` AUTO_INCREMENT = 1;
DELETE FROM `intranet`.`chemicals_role`;
ALTER TABLE `intranet`.`chemicals_role` AUTO_INCREMENT = 1;
DELETE FROM `intranet`.`chemicals_supplier`;
ALTER TABLE `intranet`.`chemicals_supplier` AUTO_INCREMENT = 1;
DELETE FROM `intranet`.`chemicals_contact`;
ALTER TABLE `intranet`.`chemicals_contact` AUTO_INCREMENT = 1;