DELETE FROM `she`.`chemicals_signal`;
ALTER TABLE `she`.`chemicals_signal` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_pictogram`;
ALTER TABLE `she`.`chemicals_pictogram` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_extendedsafetydatasheet`;
ALTER TABLE `she`.`chemicals_extendedsafetydatasheet` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_safetydatasheet`;
ALTER TABLE `she`.`chemicals_safetydatasheet` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_document`;
ALTER TABLE `she`.`chemicals_document` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_reachdocument`;
ALTER TABLE `she`.`chemicals_reachdocument` AUTO_INCREMENT = 1;
DELETE FROM `she`.`chemicals_sevesodocument`;
ALTER TABLE `she`.`chemicals_sevesodocument` AUTO_INCREMENT = 1;
DELETE FROM `she`.`filer_image` WHERE `file_ptr_id` > 99;
ALTER TABLE `she`.`filer_image` AUTO_INCREMENT = 100;
DELETE FROM `she`.`filer_file` WHERE `id` > 99;
ALTER TABLE `she`.`filer_file` AUTO_INCREMENT = 100;
